spring:
  application:
    name: aluno-api-first

server:
  port: 8080
  servlet:
    context-path: /api

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operationsSorter: method
    tagsSorter: alpha
    tryItOutEnabled: true
    filter: true
    display-request-duration: true

logging:
  level:
    com.example.aluno: DEBUG
    org.springframework.web: INFO
